spring.application.name=ms-consumidor
# Configuración Oracle
spring.datasource.username=transporte
spring.datasource.password=Passw0rd1234
# @ es el alias que está dentro del archivo tnsnames.ora de tu wallet
spring.datasource.url=jdbc:oracle:thin:@u0g12ofrwn43uj0p_high?TNS_ADMIN=/app/wallet

# JPA - Para que cree la tabla automáticamente si no existe (solo para desarrollo)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.listener.simple.acknowledge-mode=manual